name: Jason D Cass
favicon: null
layout_spectrum: 0.7272726877126843
typography_spectrum: 0.40476262429729104
title: The story of a person
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#27272d'
    - '#e4ddcf'
    - '#8d615e'
    - '#c7836c'
    - '#c7b19d'
  brandStrength: 0.625
  lightness: 0.8800567747093737
  saturation: 0.24495247681625187
  rhythmicContrast: 0.20468320092186332
purpose: []
